#include <iostream>
#include <iomanip>
#include <string>
#include <cstring>
using namespace std;

string buku[99][8] = 
{
    {"Bumi Manusia", "Pramoedya Ananta Toer", "Hasta Mitra", "1980", "Fiksi Sejarah", "Indonesia", "Tersedia"},
    {"Anak Semua Bangsa", "Pramoedya Ananta Toer", "Hasta Mitra", "1980", "Fiksi Sejarah", "Indonesia", "Tersedia"},
    {"Jejak Langkah", "Pramoedya Ananta Toer", "Hasta Mitra", "1985", "Fiksi Sejarah", "Indonesia", "Tersedia"},
    {"Rumah Kaca", "Pramoedya Ananta Toer", "Hasta Mitra", "1988", "Fiksi Sejarah", "Indonesia", "Tersedia"},
    {"Ziarah", "Iwan Simatupang", "Balai Pustaka", "1969", "Fiksi", "Indonesia", "Tersedia"},
    {"Lelaki Harimau", "Eka Kurniawan", "Gramedia Pustaka Utama", "2004", "Realisme Magis", "Indonesia", "Tersedia"},
    {"Cantik Itu Luka", "Eka Kurniawan", "Gramedia Pustaka Utama", "2014", "Fiksi", "Indonesia", "Tersedia"},
    {"Laut Bercerita", "Leila S. Chudori", "Gramedia Pustaka Utama", "2013", "Fiksi", "Indonesia", "Tersedia"},
    {"Saman", "Ayu Utami", "Gramedia Pustaka Utama", "1998", "Fiksi", "Indonesia", "Tersedia"},
    {"Supernova", "Dee Lestari", "Gramedia Pustaka Utama", "2001", "Fiksi", "Indonesia", "Tersedia"},
    {"Tetralogi Laskar Pelangi", "Andrea Hirata", "Bentang Pustaka", "2005", "Fiksi", "Indonesia", "Tersedia"},
    {"Anak Bajang Menggiring Angin", "Sindhunata", "Penerbit Buku Kompas", "1975", "Fiksi", "Indonesia", "Tersedia"},
    {"Para Priyayi", "Umar Kayam", "Penerbit Buku Kompas", "1980", "Fiksi", "Indonesia", "Tersedia"},
    {"Burung-Burung Manyar", "Y.B. Mangunwijaya", "Penerbit Buku Kompas", "1981", "Fiksi", "Indonesia", "Tersedia"},
    {"Pulang", "Leila S. Chudori", "Gramedia Pustaka Utama", "2012", "Fiksi", "Indonesia", "Tersedia"},
    {"Bumi Manusia", "Pramoedya Ananta Toer", "Hasta Mitra", "1980", "Fiksi Sejarah", "Indonesia", "Tersedia"},
    {"Anak Semua Bangsa", "Pramoedya Ananta Toer", "Hasta Mitra", "1980", "Fiksi Sejarah", "Indonesia", "Tersedia"},
    {"Jejak Langkah", "Pramoedya Ananta Toer", "Hasta Mitra", "1985", "Fiksi Sejarah", "Indonesia", "Tersedia"},
    {"Rumah Kaca", "Pramoedya Ananta Toer", "Hasta Mitra", "1988", "Fiksi Sejarah", "Indonesia", "Tersedia"},
    {"Ziarah", "Iwan Simatupang", "Balai Pustaka", "1969", "Fiksi", "Indonesia", "Tersedia"},
    {"The Girl with the Dragon Tattoo", "Stieg Larsson", "Norstedts", "2005", "Thriller", "Sweden", "Tersedia"},
    {"Memoirs of a Geisha", "Arthur Golden", "Scribner", "2005", "Historical Fiction", "Japan", "Tersedia"},
    {"The Alchemist", "Paulo Coelho", "HarperCollins", "1988", "Fantasy", "Brazil", "Tersedia"},
    {"Americanah", "Chimamanda Ngozi Adichie", "Knopf", "2013", "Fiction", "Nigeria", "Tersedia"},
    {"Karnali Blues", "Buddhisagar", "FinePrint", "2016", "Fiction", "Nepal", "Tersedia"},
    {"The Naked Don't Fear the Water", "Matthieu Aikins", "HarperCollins", "2021", "Fiction", "Afghanistan", "Tersedia"},
    {"The House of Mirth", "Edith Wharton", "Scribner", "1905", "Novel", "USA", "Tersedia"},
    {"Crime and Punishment", "Fyodor Dostoevsky", "The Russian Messenger", "1866", "Crime", "Russia", "Tersedia"},
    {"East of Eden", "John Steinbeck", "Viking Press", "1952", "Novel", "USA", "Tersedia"},
    {"The Time Traveler's Wife", "Audrey Niffenegger", "MacAdam/Cage", "2003", "Science Fiction", "USA", "Tersedia"},
    {"The Age of A.I.", "Henry Kissinger, Eric Schmidt, Daniel Huttenlocher", "Liveright", "2021", "Non-Fiction", "USA", "Tersedia"},
    {"Doing Agile Right", "Darrell K. Rigby, Sarah Elk, Steve Berez", "Harvard Business Review Press", "2020", "Business", "USA", "Tersedia"},
    {"Steve Jobs", "Walter Isaacson", "Simon & Schuster", "2011", "Biography", "USA", "Tersedia"},
    {"The Innovators", "Walter Isaacson", "Simon & Schuster", "2014", "Biography", "USA", "Tersedia"},
    {"The Second Machine Age", "Erik Brynjolfsson, Andrew McAfee", "W.W. Norton & Company", "2014", "Non-Fiction", "USA", "Tersedia"},
    {"The Master Switch", "Tim Wu", "Knopf", "2011", "Non-Fiction", "USA", "Tersedia"},
    {"The Singularity is Near", "Ray Kurzweil", "Viking", "2005", "Non-Fiction", "USA", "Tersedia"},
    {"The Road Ahead", "Bill Gates", "Viking", "1995", "Non-Fiction", "USA", "Tersedia"},
    {"The Innovators DNA", "Dyer, Gregersen, Christensen", "Harvard Business Review Press", "2013", "Business", "USA", "Tersedia"},
    {"The Industries of the Future", "Alec Ross", "Simon & Schuster", "2016", "Non-Fiction", "USA", "Tersedia"},
    {"The Bible", "Various", "Various", "Various", "Religious", "Various", "Tersedia"},
    {"The Quran", "Various", "Various", "Various", "Religious", "Various", "Tersedia"},
    {"The Bhagavad Gita", "Various", "Various", "Various", "Religious", "India", "Tersedia"},
    {"The Dhammapada", "Various", "Various", "Various", "Religious", "India", "Tersedia"},
    {"The Book of Mormon", "Various", "Various", "1830", "Religious", "USA", "Tersedia"},
    {"The Tao Te Ching", "Laozi", "Various", "6666", "Religious", "China", "Tersedia"},
    {"The Torah", "Various", "Various", "Various", "Religious", "Israel", "Tersedia"},
    {"The Confessions", "St. Augustine", "Various", "397", "Religious", "Roman Empire", "Tersedia"},
    {"The Zohar", "Various", "Various", "1333", "Mystical", "Spain", "Tersedia"},
    {"The Upanishads", "Various", "Various", "1000", "Religious", "India", "Tersedia"},
    {"Python Crash Course", "Eric Matthes", "No Starch Press", "2015", "Computer Science", "USA", "Tersedia"},
    {"Eloquent JavaScript", "Marijn Haverbeke", "No Starch Press", "2011", "Computer Science", "USA", "Tersedia"},
    {"Learning Python", "Mark Lutz", "O'Reilly Media", "2013", "Computer Science", "USA", "Tersedia"},
    {"Head First Java", "Kathy Sierra, Bert Bates", "O'Reilly Media", "2003", "Computer Science", "USA", "Tersedia"},
    {"You Don't Know JS", "Kyle Simpson", "O'Reilly Media", "2014", "Computer Science", "USA", "Tersedia"},
    {"Introduction to the Theory of Computation", "Michael Sipser", "Cengage Learning", "1996", "Computer Science", "USA", "Tersedia"},
    {"The Mythical Man-Month", "Frederick P. Brooks Jr.", "Addison-Wesley", "1975", "Computer Science", "USA", "Tersedia"},
    {"Artificial Intelligence: A Modern Approach", "Stuart Russell, Peter Norvig", "Prentice Hall", "1995", "Computer Science", "USA", "Tersedia"},
    {"The Structure and Interpretation of Computer Programs", "Harold Abelson, Gerald Jay Sussman", "MIT Press", "1996", "Computer Science", "USA", "Tersedia"},
    {"Compilers: Principles, Techniques, and Tools", "Alfred V. Aho, Monica S. Lam, Ravi Sethi, Jeffrey D. Ullman", "Addison-Wesley", "1986", "Computer Science", "USA", "Tersedia"},
    {"The Haunting of Hill House", "Shirley Jackson", "Penguin Books", "1959", "Horror", "USA", "Tersedia"},
    {"Dracula", "Bram Stoker", "Archibald Constable and Company", "1897", "Horror", "UK", "Tersedia"},
    {"Frankenstein", "Mary Shelley", "Lackington, Hughes, Harding, Mavor & Jones", "1818", "Horror", "UK", "Tersedia"},
    {"The Shining", "Stephen King", "Doubleday", "1977", "Horror", "USA", "Tersedia"},
    {"House of Leaves", "Mark Z. Danielewski", "Pantheon Books", "2000", "Horror", "USA", "Tersedia"},
    {"The Exorcist", "William Peter Blatty", "Harper & Row", "1971", "Horror", "USA", "Tersedia"},
    {"It", "Stephen King", "Viking Press", "1986", "Horror", "USA", "Tersedia"},
    {"The Turn of the Screw", "Henry James", "The Macmillan Company", "1898", "Horror", "UK", "Tersedia"},
    {"The Silence of the Lambs", "Thomas Harris", "St. Martin's Press", "1988", "Horror", "USA", "Tersedia"},
    {"The Girl Who Loved Tom Gordon", "Stephen King", "Scribner", "1999", "Horror", "USA", "Tersedia"},
    {"Antkind", "Charlie Kaufman", "HarperCollins", "2020", "Komedi", "USA", "Tersedia"},
    {"A Confederacy of Dunces", "John Kennedy Toole", "Louisiana State University Press", "1980", "Komedi", "USA", "Tersedia"},
    {"Shit, Actually", "Lindy West", "Hachette Books", "2020", "Komedi", "USA", "Tersedia"},
    {"Me Talk Pretty One Day", "David Sedaris", "Little, Brown and Company", "2000", "Komedi", "USA", "Tersedia"},
    {"Are You There, Vodka? It's Me, Chelsea", "Chelsea Handler", "Simon & Schuster", "2008", "Komedi", "USA", "Tersedia"},
    {"Pride and Prejudice", "Jane Austen", "Penguin Classics", "1813", "Romance", "UK", "Tersedia"},
    {"Outlander", "Diana Gabaldon", "Delacorte Press", "1991", "Romance", "USA", "Tersedia"},
    {"Jane Eyre", "Charlotte Brontë", "Smith, Elder & Co.", "1847", "Romance", "UK", "Tersedia"},
    {"Gone with the Wind", "Margaret Mitchell", "Macmillan Publishers", "1936", "Romance", "USA", "Tersedia"},
    {"The Notebook", "Nicholas Sparks", "Grand Central Publishing", "1996", "Romance", "USA", "Tersedia"},
    {"The Hobbit", "J.R.R. Tolkien", "George Allen & Unwin", "1937", "Adventure", "UK", "Tersedia"},
    {"Treasure Island", "Robert Louis Stevenson", "Cassell & Co.", "1883", "Adventure", "UK", "Tersedia"},
    {"The Adventures of Tom Sawyer", "Mark Twain", "American Publishing Company", "1876", "Adventure", "USA", "Tersedia"},
    {"Around the World in Eighty Days", "Jules Verne", "Pierre-Jules Hetzel", "1872", "Adventure", "France", "Tersedia"},
    {"The Call of the Wild", "Jack London", "Macmillan Publishers", "1903", "Adventure", "USA", "Tersedia"},
    {"The Hound of the Baskervilles", "Arthur Conan Doyle", "George Newnes Ltd", "1902", "Misteri", "UK", "Tersedia"},
    {"Gone Girl", "Gillian Flynn", "Crown Publishing Group", "2012", "Misteri", "USA", "Tersedia"},
    {"The Girl with the Dragon Tattoo", "Stieg Larsson", "Alfred A. Knopf", "2005", "Misteri", "Sweden", "Tersedia"},
    {"Murder on the Orient Express", "Agatha Christie", "Collins Crime Club", "1934", "Misteri", "UK", "Tersedia"},
    {"Big Little Lies", "Liane Moriarty", "Penguin Books", "2014", "Misteri", "Australia", "Tersedia"},
    {"American Psycho", "Bret Easton Ellis", "Vintage Books", "1991", "Gore", "Amerika", "Tersedia"},
    {"The Silence of the Lambs", "Thomas Harris", "St. Martin's Press", "1988", "Gore", "Amerika", "Tersedia"},
    {"House of Leaves", "Mark Z. Danielewski", "Pantheon Books", "2000", "Gore", "Amerika", "Tersedia"},
    {"Misery", "Stephen King", "Viking Penguin", "1987", "Gore", "Amerika", "Tersedia"},
    {"Battle Royale", "Koushun Takami", "Tokyo Sogensha", "1999", "Gore", "Jepang", "Tersedia"},
    {"Trainspotting", "Irvine Welsh", "Secker & Warburg", "1993", "Action", "Skotlandia", "Tersedia"},
    {"The Girl with the Dragon Tattoo", "Stieg Larsson", "Norstedts Förlag", "2005", "Action", "Swedia", "Tersedia"},
    {"I Am Legend", "Richard Matheson", "Gold Medal Books", "1954", "Action", "Amerika", "Tersedia"},
    {"World War Z", "Max Brooks", "Crown Publishers", "2006", "Action", "Amerika", "Tersedia"}
};
